pipeline:
  name: Build terraform_azure
  identifier: Build_terraform_azure_1709193266189
  projectIdentifier: Azure_cloud
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: print terraform version
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      terraform --version
                      echo "welcome to terraform"
              - step:
                  type: Run
                  name: terraform_init
                  identifier: az_login
                  spec:
                    shell: Sh
                    command: "terraform init "
              - step:
                  type: Run
                  name: azlogin
                  identifier: azlogin
                  spec:
                    shell: Sh
                    command: az login
              - step:
                  type: Run
                  name: terraform_plan
                  identifier: terraform_plan
                  spec:
                    shell: Sh
                    command: terraform plan -var="resource_group_name=uma-epp"
              - step:
                  type: Run
                  name: terraform_apply
                  identifier: terraform_apply
                  spec:
                    shell: Sh
                    command: terraform apply -var="resource_group_name=uma-epp" -auto-approve
              - step:
                  type: Run
                  name: terraform_destroy
                  identifier: terraform_destroy
                  spec:
                    shell: Sh
                    command: terraform destroy -auto-approve
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: terraform_azure
        build: <+input>
