pipeline:
  name: Build terraform_azure
  identifier: Build_terraform_azure_1709193266189
  projectIdentifier: Azure_cloud
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: print terraform version
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      terraform --version
                      echo "welcome to terraform"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: terraform_azure
        build: <+input>
